### Login
POST http://localhost:3000/login
Content-Type: application/json

{
"username": "player",
"password": "player"
}

> {% client.global.set("token", response.body.token) %}

### Create Question
POST http://localhost:3000/questions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Forth Question",
  "question": "An easy question?",
  "option1": "1",
  "option2": "2",
  "option3": "3",
  "option4": "4",
  "answer": 1,
  "category": null,
  "difficulty": "easy",
  "relatedQuestions": [1, 2]
}

### Get Question
GET http://localhost:3000/questions/2
Authorization: Bearer {{token}}

### Update Question
PUT http://localhost:3000/questions/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Second Question",
  "question": "Updated question",
  "option1": "11",
  "option2": "21",
  "option3": "31",
  "option4": "41",
  "answer": 1,
  "category": 1,
  "difficulty": "hard",
  "relatedQuestions": [1, 2]
}

### Delete Question
DELETE http://localhost:3000/questions/1
Authorization: Bearer {{token}}

### List Questions
GET http://localhost:3000/questions?page=0&title=question&category=1
Authorization: Bearer {{token}}

### Get Random Question
GET http://localhost:3000/questions/random
Authorization: Bearer {{token}}

### Answer Question
POST http://localhost:3000/questions/3/answer
Authorization: Bearer {{token}}
Content-Type: application/json

{
"answer": 1
}

### Get Scoreboard
GET http://localhost:3000/scoreboard?page=0&pageSize=10
Authorization: Bearer {{token}}
